### ISSUE TITLE
Error when updating one cheat (app not responding)

### ISSUE THREAD

**Issue by Antololozozo** [zzpong/Interactive-ASM-Cheats-Updater#4]
Hello. Thank you for this tool !  I updated a lot of cheats.

I have a problem with one : I updated all other cheats of the game, but for one of them the app crash.

First, when I paste my cheat, I have this message : 

![image](https://github.com/zzpong/Interactive-ASM-Cheats-Updater/assets/144557954/9e389f32-b181-4b9f-8e19-08fb3c769fd1)

On another cheat, I had the same, the app was very slow (not responding) to update one line but it worked (2 hours loading).

But on this cheat, the app  is not responding with one line. I tried more than 20 hours (twice) but not any result. I tried to skip this line, but it also freeze.

Can you help me ?

**Comment by zzpong** [comment]
Hi there,
"First, when I paste my cheat, I have this message"
A: This message shows that the 08x long codes are equally shorted to 04x ones, without any change.

"On another cheat, I had the same, the app was very slow (not responding) to update one line but it worked (2 hours loading)"
A: I think it was searching some features maybe, but never seen this situation before.

“But on this cheat, the app is not responding with one line. I tried to skip this line, but it also freeze.”
A: In most cases, this happened because the features requested are not found, e.g. wrong cheat codes version that don't match the game. But I'm not sure. Or maybe there are some new features that the software cannot recognize.

Could you send me the failed cheat codes and two "main.nso" files (would be in the same folder of the games) so I can check it?

**Comment by Antololozozo** [comment]
Thank you very much !

[https://drive.google.com/file/d/1FeT5h6q5dgn6QEvGkehcMoZLGVE2wkqy/view?usp=sharing](url)

In the zip, you can find the two main.nso and the cheat in a txt file.

**Comment by zzpong** [comment]
Fixed~ Please download the newest release.
Thanks for the great feedback!

**Comment by Antololozozo** [comment]
It works with your new release ! In the app and in the game !

Thank you very much !

**Comment by zzpong** [comment]
Glad it helps~

**Comment by Antololozozo** [comment]
Your tool is very useful !
